from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.db.models import Count
from django.db.models.functions import TruncDate
from .models import Feedback
from .serilaizers import FeedbackSerializer
from .sentiment import analyze_sentiment
from datetime import date
from art_int.ai import AIModel

class FeedbackListCreate(APIView):
    def get(self, request):
        feedback = Feedback.objects.order_by("-created_at")
        serializer = FeedbackSerializer(feedback, many=True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = FeedbackSerializer(data=request.data)
        if serializer.is_valid():
            score, label = analyze_sentiment(serializer.validated_data["feedback_text"])
            feedback = Feedback.objects.create(
                name = serializer.validated_data.get("name"),
                email = serializer.validated_data.get("email"),
                feedback_text = serializer.validated_data["feedback_text"],
                sentiment_score=score,
                sentiment_label = label
            )
            return Response(FeedbackSerializer(feedback).data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class FeedbackListCreateAI(APIView):
    def get(self, request):
        # Use AI to create the feedback
        ai_model = AIModel()
        ai_data = ai_model.get_ai_data()
        serializer = FeedbackSerializer(data=ai_data)
        if serializer.is_valid():
            score, label = analyze_sentiment(serializer.validated_data["feedback_text"])
            serializer.validated_data["feedback_text"] += " - (This review was generated by AI)."
            feedback = Feedback.objects.create(
                name = serializer.validated_data.get("name"),
                email = serializer.validated_data.get("email"),
                feedback_text = serializer.validated_data["feedback_text"],
                sentiment_score=score,
                sentiment_label = label
            )
            return Response(FeedbackSerializer(feedback).data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)    

class FeedbackSentimentDateRange(APIView):
    def get(self, request):
        from_date = request.query_params.get("from_date")
        to_date = request.query_params.get("to_date")
        if not request.query_params.get("sentiment"):
            feedback = Feedback.objects.filter(created_at__gte=f"{from_date}T00:00:00.000Z", created_at__lte=f"{to_date}T23:59:59.999Z")
        else:
            sentiment = request.query_params.get("sentiment")
            feedback = Feedback.objects.filter(created_at__gte=f"{from_date}T00:00:00.000Z", created_at__lte=f"{to_date}T23:59:59.999Z", sentiment_label=sentiment)
        serializer = FeedbackSerializer(feedback, many=True)
        return Response(serializer.data)
    
    
class FeedbackStats(APIView):
    def get(self, request):
        total = Feedback.objects.count()
        distribution = Feedback.objects.values("sentiment_label").annotate(count=Count("id"))
        trend = (
            Feedback.objects.annotate(date=TruncDate("created_at"))
            .values("date", "sentiment_label").annotate(count=Count("id"))
            .order_by("date")
        )
        return Response({
            "total_feedback": total,
            "sentiment_distribution": distribution,
            "trend_over_time": trend
        })